import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.vue',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Cairo', 'Inter', ...defaultTheme.fontFamily.sans],
                "headline-lg": ["Cairo", "Inter"],
                "label-md": ["Cairo", "Inter"],
                "body-md": ["Cairo", "Inter"],
                "headline-md": ["Cairo", "Inter"],
                "label-sm": ["Cairo", "Inter"],
                "display-lg": ["Cairo", "Inter"],
                "body-lg": ["Cairo", "Inter"],
                "headline-lg-mobile": ["Cairo", "Inter"],
                "arabic": ["Cairo", "Inter"],
            },
            colors: {
                "on-tertiary": "rgb(var(--color-on-tertiary) / <alpha-value>)",
                "inverse-on-surface": "rgb(var(--color-inverse-on-surface) / <alpha-value>)",
                "error": "rgb(var(--color-error) / <alpha-value>)",
                "on-secondary-fixed": "rgb(var(--color-on-secondary-fixed) / <alpha-value>)",
                "secondary": "rgb(var(--color-secondary) / <alpha-value>)",
                "surface-container-highest": "rgb(var(--color-surface-container-highest) / <alpha-value>)",
                "tertiary-container": "rgb(var(--color-tertiary-container) / <alpha-value>)",
                "surface-container-lowest": "rgb(var(--color-surface-container-lowest) / <alpha-value>)",
                "on-primary-fixed": "rgb(var(--color-on-primary-fixed) / <alpha-value>)",
                "on-primary-fixed-variant": "rgb(var(--color-on-primary-fixed-variant) / <alpha-value>)",
                "secondary-fixed": "rgb(var(--color-secondary-fixed) / <alpha-value>)",
                "surface-container": "rgb(var(--color-surface-container) / <alpha-value>)",
                "outline": "rgb(var(--color-outline) / <alpha-value>)",
                "on-secondary": "rgb(var(--color-on-secondary) / <alpha-value>)",
                "primary-fixed": "rgb(var(--color-primary-fixed) / <alpha-value>)",
                "on-error-container": "rgb(var(--color-on-error-container) / <alpha-value>)",
                "secondary-fixed-dim": "rgb(var(--color-secondary-fixed-dim) / <alpha-value>)",
                "inverse-surface": "rgb(var(--color-inverse-surface) / <alpha-value>)",
                "outline-variant": "rgb(var(--color-outline-variant) / <alpha-value>)",
                "on-tertiary-container": "rgb(var(--color-on-tertiary-container) / <alpha-value>)",
                "surface-container-high": "rgb(var(--color-surface-container-high) / <alpha-value>)",
                "secondary-container": "rgb(var(--color-secondary-container) / <alpha-value>)",
                "on-tertiary-fixed": "rgb(var(--color-on-tertiary-fixed) / <alpha-value>)",
                "primary-container": "rgb(var(--color-primary-container) / <alpha-value>)",
                "surface-dim": "rgb(var(--color-surface-dim) / <alpha-value>)",
                "on-surface": "rgb(var(--color-on-surface) / <alpha-value>)",
                "on-secondary-fixed-variant": "rgb(var(--color-on-secondary-fixed-variant) / <alpha-value>)",
                "on-secondary-container": "rgb(var(--color-on-secondary-container) / <alpha-value>)",
                "tertiary-fixed": "rgb(var(--color-tertiary-fixed) / <alpha-value>)",
                "on-primary-container": "rgb(var(--color-on-primary-container) / <alpha-value>)",
                "error-container": "rgb(var(--color-error-container) / <alpha-value>)",
                "on-background": "rgb(var(--color-on-background) / <alpha-value>)",
                "surface-container-low": "rgb(var(--color-surface-container-low) / <alpha-value>)",
                "tertiary": "rgb(var(--color-tertiary) / <alpha-value>)",
                "on-primary": "rgb(var(--color-on-primary) / <alpha-value>)",
                "background": "rgb(var(--color-background) / <alpha-value>)",
                "on-error": "rgb(var(--color-on-error) / <alpha-value>)",
                "primary-fixed-dim": "rgb(var(--color-primary-fixed-dim) / <alpha-value>)",
                "on-tertiary-fixed-variant": "rgb(var(--color-on-tertiary-fixed-variant) / <alpha-value>)",
                "inverse-primary": "rgb(var(--color-inverse-primary) / <alpha-value>)",
                "surface-bright": "rgb(var(--color-surface-bright) / <alpha-value>)",
                "on-surface-variant": "rgb(var(--color-on-surface-variant) / <alpha-value>)",
                "surface": "rgb(var(--color-surface) / <alpha-value>)",
                "surface-variant": "rgb(var(--color-surface-variant) / <alpha-value>)",
                "primary": "rgb(var(--color-primary) / <alpha-value>)",
                "surface-tint": "rgb(var(--color-surface-tint) / <alpha-value>)",
                "tertiary-fixed-dim": "rgb(var(--color-tertiary-fixed-dim) / <alpha-value>)",
                "secondary-fixed-variant": "rgb(var(--color-secondary-fixed-variant) / <alpha-value>)",
                "on-primary-container-high": "rgb(var(--color-on-primary-container-high) / <alpha-value>)",
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px"
            },
            spacing: {
                gutter: "1.5rem",
                "margin-mobile": "1rem",
                xs: "0.5rem",
                md: "1.5rem",
                lg: "2rem",
                "margin-desktop": "5rem",
                xl: "3rem",
                sm: "1rem",
                base: "4px"
            },
            fontSize: {
                "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}],
                "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "600"}],
                "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
                "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
                "label-sm": ["12px", {"lineHeight": "1.4", "fontWeight": "500"}],
                "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
                "headline-lg-mobile": ["24px", {"lineHeight": "1.2", "fontWeight": "700"}]
            }
        },
    },

    plugins: [forms],
};
